-- Allow public/anon to browse active products (public catalog)
GRANT SELECT ON public.products TO anon;
CREATE POLICY "products_public_read" ON public.products
  FOR SELECT TO anon
  USING (active = true);

INSERT INTO public.products (sku, name, category, uom) VALUES
('PAP-001', 'A4 Copy Paper 80gsm', 'Paper', 'per ream / box of 5 / carton'),
('PAP-002', 'A3 Copy Paper 80gsm', 'Paper', 'per ream / carton'),
('PAP-003', 'A4 Coloured Paper (Assorted)', 'Paper', 'per ream'),
('PAP-004', 'A4 Bond Paper 100gsm', 'Paper', 'per ream'),
('PAP-005', 'Photocopy Paper 70gsm', 'Paper', 'per ream / carton'),
('PAP-006', 'Carbonless NCR Paper', 'Paper', 'per ream'),
('PAP-007', 'Sticky Notes 3x3 (Assorted)', 'Paper', 'per pack of 12'),
('PAP-008', 'Notebooks A4 Hardcover', 'Paper', 'per unit / per dozen'),
('PAP-009', 'Counter Books A4 (96 / 192 / 384 pages)', 'Paper', 'per unit'),
('PAP-010', 'Receipt Books (Duplicate / Triplicate)', 'Paper', 'per unit'),
('PAP-011', 'Delivery Note Books', 'Paper', 'per unit'),
('PAP-012', 'Invoice Books', 'Paper', 'per unit'),
('STN-001', 'Biro Pens (Blue / Black / Red)', 'Stationery', 'per box of 50'),
('STN-002', 'Gel Pens (Assorted Colours)', 'Stationery', 'per box of 12'),
('STN-003', 'Permanent Markers', 'Stationery', 'per set of 4'),
('STN-004', 'Whiteboard Markers', 'Stationery', 'per set of 4'),
('STN-005', 'Highlighters (Assorted)', 'Stationery', 'per pack of 6'),
('STN-006', 'HB Pencils', 'Stationery', 'per box of 12'),
('STN-007', 'Mechanical Pencils 0.5mm', 'Stationery', 'per pack'),
('STN-008', 'Eraser & Sharpener Set', 'Stationery', 'per pack'),
('STN-009', 'Wooden Rulers 30cm', 'Stationery', 'per dozen'),
('STN-010', 'Heavy Duty Stapler', 'Stationery', 'per unit'),
('STN-011', 'Standard Stapler + Pins', 'Stationery', 'per unit'),
('STN-012', 'Staple Pins No. 24/6', 'Stationery', 'per box'),
('STN-013', 'Paper Clips (Assorted Sizes)', 'Stationery', 'per box'),
('STN-014', 'Binder Clips (Assorted)', 'Stationery', 'per pack'),
('STN-015', 'Punch Machine 2-Hole', 'Stationery', 'per unit'),
('STN-016', 'Heavy Duty 4-Hole Punch', 'Stationery', 'per unit'),
('STN-017', 'Scissors (Office Grade)', 'Stationery', 'per unit'),
('STN-018', 'Glue Sticks 40g', 'Stationery', 'per pack of 12'),
('STN-019', 'Liquid Glue 250ml', 'Stationery', 'per unit'),
('STN-020', 'Correction Fluid', 'Stationery', 'per unit'),
('STN-021', 'Correction Tape', 'Stationery', 'per pack'),
('STN-022', 'Manila Envelopes A4', 'Stationery', 'per box of 50'),
('STN-023', 'Brown Envelopes A5 / A4 / A3', 'Stationery', 'per box'),
('STN-024', 'Window Envelopes DL', 'Stationery', 'per box of 100'),
('STN-025', 'Box Files (Foolscap)', 'Stationery', 'per unit / per dozen'),
('STN-026', 'Lever Arch Files', 'Stationery', 'per unit / per dozen'),
('STN-027', 'Spring Files', 'Stationery', 'per dozen'),
('STN-028', 'Document Wallets', 'Stationery', 'per pack'),
('STN-029', 'Clear Sheet Protectors A4', 'Stationery', 'per pack of 100'),
('STN-030', 'Ring Binders 2-Ring / 4-Ring', 'Stationery', 'per unit'),
('STN-031', 'Index Dividers (1-12 / A-Z)', 'Stationery', 'per pack'),
('STN-032', 'ID Card Holders + Lanyards', 'Stationery', 'per pack'),
('STN-033', 'Desk Organiser Tray', 'Stationery', 'per unit'),
('STN-034', 'Letter Trays 3-Tier', 'Stationery', 'per unit'),
('STN-035', 'Whiteboard 4ft x 3ft', 'Stationery', 'per unit'),
('STN-036', 'Cork Notice Board', 'Stationery', 'per unit'),
('STN-037', 'Flipchart Stand + Pads', 'Stationery', 'per set'),
('STN-038', 'Date / Number Stamps', 'Stationery', 'per unit'),
('STN-039', 'Stamp Pads + Refill Ink', 'Stationery', 'per unit'),
('STN-040', 'Calculators (Desk / Scientific)', 'Stationery', 'per unit'),
('TON-001', 'HP 85A Toner Cartridge', 'Toner & Ink', 'per unit'),
('TON-002', 'HP 12A Toner Cartridge', 'Toner & Ink', 'per unit'),
('TON-003', 'HP 17A / 30A / 79A Toner', 'Toner & Ink', 'per unit'),
('TON-004', 'HP 410A Colour Toner Set', 'Toner & Ink', 'per set of 4'),
('TON-005', 'Canon 045 Toner', 'Toner & Ink', 'per unit'),
('TON-006', 'Canon 325 / 337 Toner', 'Toner & Ink', 'per unit'),
('TON-007', 'Brother TN-2380 Toner', 'Toner & Ink', 'per unit'),
('TON-008', 'Samsung MLT-D101S Toner', 'Toner & Ink', 'per unit'),
('TON-009', 'Kyocera TK Series Toner', 'Toner & Ink', 'per unit'),
('TON-010', 'Epson 003 Ink Bottles (CMYK)', 'Toner & Ink', 'per set'),
('TON-011', 'Epson 664 Ink Bottles (CMYK)', 'Toner & Ink', 'per set'),
('TON-012', 'HP GT53 Black Ink', 'Toner & Ink', 'per unit'),
('TON-013', 'Ribbon Cartridges (Dot Matrix)', 'Toner & Ink', 'per unit'),
('FUR-001', 'Executive Office Chair (Leather)', 'Furniture', 'per unit'),
('FUR-002', 'Ergonomic Mesh Office Chair', 'Furniture', 'per unit'),
('FUR-003', 'Visitor / Reception Chair', 'Furniture', 'per unit'),
('FUR-004', 'Stackable Conference Chair', 'Furniture', 'per unit'),
('FUR-005', 'Executive Desk 1.6m', 'Furniture', 'per unit'),
('FUR-006', 'Workstation Desk (L-Shape)', 'Furniture', 'per unit'),
('FUR-007', 'Office Workstations (4-Pod)', 'Furniture', 'per set'),
('FUR-008', 'Conference Table 8-Seater', 'Furniture', 'per unit'),
('FUR-009', 'Boardroom Table 12-Seater', 'Furniture', 'per unit'),
('FUR-010', 'Reception Counter / Desk', 'Furniture', 'per unit'),
('FUR-011', 'Office Filing Cabinet 4-Drawer', 'Furniture', 'per unit'),
('FUR-012', 'Mobile Pedestal 3-Drawer', 'Furniture', 'per unit'),
('FUR-013', 'Bookshelf / Open Shelving Unit', 'Furniture', 'per unit'),
('FUR-014', 'Lockers (6 / 9 / 12 Compartments)', 'Furniture', 'per unit'),
('FUR-015', 'Fireproof Safe', 'Furniture', 'per unit'),
('FUR-016', 'Coat Stand / Hat Rack', 'Furniture', 'per unit'),
('FUR-017', 'Office Sofa Set (3+1+1)', 'Furniture', 'per set'),
('FUR-018', 'Coffee Table (Reception)', 'Furniture', 'per unit'),
('CLN-001', 'Hand Sanitiser 500ml', 'Cleaning', 'per unit / per carton'),
('CLN-002', 'Hand Sanitiser 5L Refill', 'Cleaning', 'per unit'),
('CLN-003', 'Liquid Hand Soap 5L', 'Cleaning', 'per unit'),
('CLN-004', 'Bathroom Tissue 2-Ply', 'Cleaning', 'per pack of 10 / bale'),
('CLN-005', 'Kitchen Roll / Paper Towels', 'Cleaning', 'per pack'),
('CLN-006', 'Facial Tissue Boxes', 'Cleaning', 'per pack'),
('CLN-007', 'Disinfectant 5L (Pine / Lemon)', 'Cleaning', 'per unit'),
('CLN-008', 'Multi-Surface Cleaner 5L', 'Cleaning', 'per unit'),
('CLN-009', 'Toilet Bowl Cleaner', 'Cleaning', 'per unit'),
('CLN-010', 'Glass Cleaner 500ml', 'Cleaning', 'per unit'),
('CLN-011', 'Bleach 5L', 'Cleaning', 'per unit'),
('CLN-012', 'Dishwashing Liquid 5L', 'Cleaning', 'per unit'),
('CLN-013', 'Air Freshener (Spray / Automatic)', 'Cleaning', 'per unit'),
('CLN-014', 'Mop & Bucket Set', 'Cleaning', 'per unit'),
('CLN-015', 'Industrial Mop Heads', 'Cleaning', 'per unit'),
('CLN-016', 'Brooms (Soft / Hard)', 'Cleaning', 'per unit'),
('CLN-017', 'Dustpan & Brush Set', 'Cleaning', 'per unit'),
('CLN-018', 'Microfibre Cleaning Cloths', 'Cleaning', 'per pack of 10'),
('CLN-019', 'Scouring Pads', 'Cleaning', 'per pack'),
('CLN-020', 'Garbage Bags (Heavy Duty)', 'Cleaning', 'per roll / carton'),
('CLN-021', 'Pedal Bins 30L / 50L', 'Cleaning', 'per unit'),
('CLN-022', 'Disposable Gloves (Latex / Nitrile)', 'Cleaning', 'per box of 100'),
('CLN-023', 'Face Masks 3-Ply', 'Cleaning', 'per box of 50'),
('CLN-024', 'First Aid Kit (Office Standard)', 'Cleaning', 'per unit'),
('TEC-001', 'Laser Printer A4 Mono', 'Technology', 'per unit'),
('TEC-002', 'Colour Laser Printer A4', 'Technology', 'per unit'),
('TEC-003', 'Multifunction Printer (Print/Scan/Copy)', 'Technology', 'per unit'),
('TEC-004', 'Heavy Duty Photocopier', 'Technology', 'per unit'),
('TEC-005', 'Document Scanner', 'Technology', 'per unit'),
('TEC-006', 'Paper Shredder (Cross-Cut)', 'Technology', 'per unit'),
('TEC-007', 'Laminating Machine A4 / A3', 'Technology', 'per unit'),
('TEC-008', 'Laminating Pouches A4', 'Technology', 'per pack of 100'),
('TEC-009', 'Spiral Binding Machine', 'Technology', 'per unit'),
('TEC-010', 'Binding Combs & Covers', 'Technology', 'per pack'),
('TEC-011', 'UPS 650VA / 1000VA', 'Technology', 'per unit'),
('TEC-012', 'Surge Protector Power Strips', 'Technology', 'per unit'),
('TEC-013', 'Extension Cables 4-Way / 6-Way', 'Technology', 'per unit'),
('TEC-014', 'Desktop Computer (i5 / i7)', 'Technology', 'per unit'),
('TEC-015', 'Laptop (Business Grade)', 'Technology', 'per unit'),
('TEC-016', 'LED Monitor 22" / 24"', 'Technology', 'per unit'),
('TEC-017', 'Wireless Keyboard & Mouse Set', 'Technology', 'per set'),
('TEC-018', 'USB Flash Drive 32GB / 64GB', 'Technology', 'per unit / per box of 10'),
('TEC-019', 'External Hard Drive 1TB / 2TB', 'Technology', 'per unit'),
('TEC-020', 'HDMI / VGA / USB Cables', 'Technology', 'per unit'),
('TEC-021', 'Network Switches 8 / 16 / 24 Port', 'Technology', 'per unit'),
('TEC-022', 'Wi-Fi Router (Dual Band)', 'Technology', 'per unit'),
('TEC-023', 'CCTV Camera Kit (4-Channel)', 'Technology', 'per set'),
('TEC-024', 'Projector (HD / Full HD)', 'Technology', 'per unit'),
('TEC-025', 'Projector Screen 96"', 'Technology', 'per unit'),
('TEC-026', 'Conference Speakerphone', 'Technology', 'per unit'),
('TEC-027', 'Desk Telephone (PABX)', 'Technology', 'per unit'),
('PKG-001', 'Carton Sealing Tape (Brown / Clear)', 'Packaging', 'per roll / per box'),
('PKG-002', 'Masking Tape (Assorted Sizes)', 'Packaging', 'per roll / box'),
('PKG-003', 'Double-Sided Tape', 'Packaging', 'per roll'),
('PKG-004', 'Stretch Wrap / Cling Film', 'Packaging', 'per roll'),
('PKG-005', 'Bubble Wrap (Rolls)', 'Packaging', 'per roll'),
('PKG-006', 'Corrugated Cartons (Assorted)', 'Packaging', 'per unit / per bale'),
('PKG-007', 'Mailing / Courier Bags', 'Packaging', 'per pack of 100'),
('PKG-008', 'Padded Envelopes', 'Packaging', 'per pack'),
('PKG-009', 'Strapping Bands + Buckles', 'Packaging', 'per roll'),
('PKG-010', 'Shipping Labels A4', 'Packaging', 'per pack of 100'),
('PKG-011', 'Thermal Receipt Rolls 80mm', 'Packaging', 'per box'),
('PKG-012', 'Barcode Labels (Rolls)', 'Packaging', 'per roll')
ON CONFLICT (sku) DO NOTHING;